### PR TITLE
bench: update

### PR DESCRIPTION
**Pull request by bvanjoi**
this pr brings the following changes:

1. fairer benchmark: use async io in enhanced-resolve instead of sync (It's my fault).

rust:

3db44712-75a9-4515-a80f-79a78b845dae

enhanced-resolve:

image

2. cache the symlink result:

before:

image

after: 

image

### CODE REVIEW

**Comment by Boshen** [comment]
Are we able to get the execution time from the output?

**Comment by Boshen** [comment]
ns / iter is pretty useless imo ...

**Comment by Boshen** [comment]
Can you add the bench result to README?

And even better, you can use `hyperfine`.

**Review by Boshen — CHANGES_REQUESTED** [review]
What happened to the changelog?

**Comment by bvanjoi** [comment]
> What happened to the changelog?

I removed it because it wasn't a clear description

**Review by Boshen — APPROVED** [review]

**Pull request merged**
